// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autojob.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from autojob.proto</summary>
  public static partial class AutojobReflection {

    #region Descriptor
    /// <summary>File descriptor for autojob.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AutojobReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1hdXRvam9iLnByb3RvEgVwcm90bxoMY29tbW9uLnByb3RvMrIBCg5BdXRv",
            "Sm9iU2VydmljZRI0ChRVcGRhdGVQcm9qZWN0c1N0YXR1cxIMLnByb3RvLkVt",
            "cHR5GgwucHJvdG8uRW1wdHkiABIyChJVcGRhdGVTdGFnZXNTdGF0dXMSDC5w",
            "cm90by5FbXB0eRoMLnByb3RvLkVtcHR5IgASNgoWVXBkYXRlT3RjRGV0YWls",
            "c1N0YXR1cxIMLnByb3RvLkVtcHR5GgwucHJvdG8uRW1wdHkiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
