// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxjb21tb24ucHJvdG8SBXByb3RvIgcKBUVtcHR5IhMKBUlkUmVxEgoKAmlk",
            "GAEgASgDIi0KCUJvb2xSZXBseRIgCgZyZXN1bHQYASABKA4yEC5wcm90by5C",
            "b29sVmFsdWUqLQoJQm9vbFZhbHVlEgsKB0JOb3RTZXQQABIICgRUcnVlEAES",
            "CQoFRmFsc2UQAipSCgpGYWN0b3JUeXBlEgoKBk5vdFNldBAAEhEKDUVtYWls",
            "QXV0aFR5cGUQARIRCg1QaG9uZUF1dGhUeXBlEAISEgoOR29vZ2xlQXV0aFR5",
            "cGUQAypLCghLeWNTdGFnZRILCgdLTm90U2V0EAASDwoLS3ljU3RhZ2VPbmUQ",
            "ARIPCgtLeWNTdGFnZVR3bxACEhAKDEt5Y1N0YWdlVHJlZRADKjIKCEt5Y1N0",
            "YXRlEgwKCEtTTm90U2V0EAASCgoGUGFzc2VkEAESDAoIUmVqZWN0ZWQQAipA",
            "CghVc2VyS2luZBILCgdVTm90U2V0EAASEgoOVXNlcktpbmRQZXJzb24QARIT",
            "Cg9Vc2VyS2luZENvbXBhbnkQAipUCgxJZGVudGl0eVR5cGUSCwoHSU5vdFNl",
            "dBAAEhYKEklkZW50aWZpY2F0aW9uQ2FyZBABEhAKDFBhc3Nwb3J0Q2FyZBAC",
            "Eg0KCU90aGVyQ2FyZBADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.BoolValue), typeof(global::Proto.FactorType), typeof(global::Proto.KycStage), typeof(global::Proto.KycState), typeof(global::Proto.UserKind), typeof(global::Proto.IdentityType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Empty), global::Proto.Empty.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.IdReq), global::Proto.IdReq.Parser, new[]{ "Id" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.BoolReply), global::Proto.BoolReply.Parser, new[]{ "Result" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///整形Bool值类型
  /// </summary>
  public enum BoolValue {
    [pbr::OriginalName("BNotSet")] BnotSet = 0,
    [pbr::OriginalName("True")] True = 1,
    [pbr::OriginalName("False")] False = 2,
  }

  /// <summary>
  ///二次验证类型
  /// </summary>
  public enum FactorType {
    [pbr::OriginalName("NotSet")] NotSet = 0,
    /// <summary>
    ///Email验证
    /// </summary>
    [pbr::OriginalName("EmailAuthType")] EmailAuthType = 1,
    /// <summary>
    ///手机验证
    /// </summary>
    [pbr::OriginalName("PhoneAuthType")] PhoneAuthType = 2,
    /// <summary>
    ///Google验证
    /// </summary>
    [pbr::OriginalName("GoogleAuthType")] GoogleAuthType = 3,
  }

  /// <summary>
  ///Kyc级别类型
  /// </summary>
  public enum KycStage {
    [pbr::OriginalName("KNotSet")] KnotSet = 0,
    /// <summary>
    ///一级认证
    /// </summary>
    [pbr::OriginalName("KycStageOne")] One = 1,
    /// <summary>
    ///二级认证
    /// </summary>
    [pbr::OriginalName("KycStageTwo")] Two = 2,
    /// <summary>
    ///三级认证
    /// </summary>
    [pbr::OriginalName("KycStageTree")] Tree = 3,
  }

  /// <summary>
  ///Kyc审核状态
  /// </summary>
  public enum KycState {
    /// <summary>
    ///审核中
    /// </summary>
    [pbr::OriginalName("KSNotSet")] KsnotSet = 0,
    /// <summary>
    ///审核通过
    /// </summary>
    [pbr::OriginalName("Passed")] Passed = 1,
    /// <summary>
    ///审核拒绝
    /// </summary>
    [pbr::OriginalName("Rejected")] Rejected = 2,
  }

  /// <summary>
  ///用户类型
  /// </summary>
  public enum UserKind {
    [pbr::OriginalName("UNotSet")] UnotSet = 0,
    /// <summary>
    ///普通用户
    /// </summary>
    [pbr::OriginalName("UserKindPerson")] Person = 1,
    /// <summary>
    ///公司用户
    /// </summary>
    [pbr::OriginalName("UserKindCompany")] Company = 2,
  }

  /// <summary>
  ///证件类型
  /// </summary>
  public enum IdentityType {
    [pbr::OriginalName("INotSet")] InotSet = 0,
    /// <summary>
    ///身份证
    /// </summary>
    [pbr::OriginalName("IdentificationCard")] IdentificationCard = 1,
    /// <summary>
    ///护照
    /// </summary>
    [pbr::OriginalName("PassportCard")] PassportCard = 2,
    /// <summary>
    ///其他
    /// </summary>
    [pbr::OriginalName("OtherCard")] OtherCard = 3,
  }

  #endregion

  #region Messages
  public sealed partial class Empty : pb::IMessage<Empty> {
    private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Empty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty(Empty other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty Clone() {
      return new Empty(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Empty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Empty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Empty other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed partial class IdReq : pb::IMessage<IdReq> {
    private static readonly pb::MessageParser<IdReq> _parser = new pb::MessageParser<IdReq>(() => new IdReq());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IdReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CommonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdReq(IdReq other) : this() {
      id_ = other.id_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdReq Clone() {
      return new IdReq(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IdReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IdReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IdReq other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class BoolReply : pb::IMessage<BoolReply> {
    private static readonly pb::MessageParser<BoolReply> _parser = new pb::MessageParser<BoolReply>(() => new BoolReply());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BoolReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.CommonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BoolReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BoolReply(BoolReply other) : this() {
      result_ = other.result_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BoolReply Clone() {
      return new BoolReply(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Proto.BoolValue result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.BoolValue Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BoolReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BoolReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BoolReply other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::Proto.BoolValue) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
